### ISSUE TITLE
error if "/" in stop_id

### ISSUE THREAD

**Issue by nlehuby** [thatsmydoing/gtfs.html#27]
I'm trying to use gtfs.html on a GTFS feed that has `/` in every stop_id field (for instance `node/6899034710`).

The[ stop page](https://gtfs.pleasantprogrammer.com/#stop/node/6899034710) cannot be loaded.

the browser console throws a TypeError from lodash.js file `TypeError: l is undefined`

**Comment by jayenashar** [comment]
i think the issue is in `pathToObject` https://github.com/thatsmydoing/gtfs.html/blob/2c910daf6103ec66429278013830d08a67fd0b3f/src/reducers/navigation.js#L12

i think it should be:

```
  let [type, id] = decodeURIComponent(path).substring(1).split('/', 2);
```

**Comment by thatsmydoing** [comment]
Good catch, I've pushed a fix for the issue.

**Comment by nlehuby** [comment]
Does it have been release on https://gtfs.pleasantprogrammer.com ? I can still reproduce this issue :thinking:

**Comment by thatsmydoing** [comment]
Yes, I have. I tried it and it seems to work for me. Maybe it was a caching issue? If you can still reproduce it, could you give me a sample gtfs file?

**Comment by nlehuby** [comment]
I can still reproduce :cry: Here is my [GTFS feed](https://github.com/Jungle-Bus/AbidjanTransport_gtfs_ci/raw/gh-pages/abidjan.zip), it crashes on any stop

**Comment by thatsmydoing** [comment]
Oh, you're right. I think it should be actually fixed now.

**Comment by nlehuby** [comment]
:+1: thanks
